-- IBM DB2 LUW creation script for opentmf-db-lock-service.
-- Targets DB2 LUW 11.5+ (INTEGER GENERATED BY DEFAULT AS IDENTITY, inline
-- compound SQL). Statement separator: '/' (required because this file
-- contains compound-SQL blocks with embedded semicolons). Each guard
-- catches SQLSTATE '42710' ("object name is already used") so the script
-- may be re-run safely.
--
-- Note on timestamps: DB2 LUW has no TIMESTAMP WITH TIME ZONE column type
-- (that form is DB2 for z/OS only). This script uses plain TIMESTAMP, which
-- DB2 stores without timezone information. Run both the application JVM and
-- the DB2 server with TZ = UTC to avoid drift on created_on /
-- lock_acquired_on values read back as OffsetDateTime.

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE DB_LOCK (
      id               INTEGER              GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      lock_type        CHAR(1)              NOT NULL
        CONSTRAINT CKC_LOCK_TYPE_DB_LOCK CHECK (lock_type IN (''B'',''C'',''X'',''Y'',''Z'')),
      lock_version     VARCHAR(50)          NOT NULL,
      hostname         VARCHAR(255)         NOT NULL,
      created_on       TIMESTAMP            DEFAULT CURRENT TIMESTAMP NOT NULL,
      CONSTRAINT PK_DB_LOCK PRIMARY KEY (id)
    )';
END;
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE UNIQUE INDEX NDX_LOCK_TYPE ON DB_LOCK (lock_type)';
END;
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE DB_LOCK_HISTORY (
      id               INTEGER              GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      lock_id          INTEGER              NOT NULL,
      lock_type        CHAR(1)              NOT NULL
        CONSTRAINT CKC_LOCK_TYPE_DB_LOCK_H CHECK (lock_type IN (''B'',''C'',''X'',''Y'',''Z'')),
      lock_version     VARCHAR(50)          NOT NULL,
      hostname         VARCHAR(255)         NOT NULL,
      lock_acquired_on TIMESTAMP            DEFAULT CURRENT TIMESTAMP NOT NULL,
      lock_released_on TIMESTAMP            DEFAULT CURRENT TIMESTAMP NOT NULL,
      CONSTRAINT PK_DB_LOCK_HISTORY PRIMARY KEY (id)
    )';
END;
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE INDEX NDX_DATE ON DB_LOCK_HISTORY (lock_acquired_on)';
END;
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE INDEX NDX_LOCK ON DB_LOCK_HISTORY (lock_type, lock_version)';
END;
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE DB_LOCK_LATEST (
      lock_type        CHAR(1)              NOT NULL
        CONSTRAINT CKC_LOCK_TYPE_DB_LOCK_L CHECK (lock_type IN (''B'',''C'',''X'',''Y'',''Z'')),
      lock_version     VARCHAR(50)          NOT NULL,
      hostname         VARCHAR(255)         NOT NULL,
      lock_acquired_on TIMESTAMP            NOT NULL,
      CONSTRAINT PK_DB_LOCK_LATEST PRIMARY KEY (lock_type)
    )';
END;
/
