-- H2 creation script for opentmf-db-lock-service.
-- Targets H2 2.x in its default (REGULAR) compatibility mode.

create table if not exists DB_LOCK (
   id                   INT GENERATED BY DEFAULT AS IDENTITY not null,
   lock_type            CHAR(1)              not null
      constraint CKC_LOCK_TYPE_DB_LOCK check (lock_type in ('B','C','X','Y','Z')),
   lock_version         VARCHAR(50)          not null,
   hostname             VARCHAR(255)         not null,
   created_on           TIMESTAMP WITH TIME ZONE not null default CURRENT_TIMESTAMP,
   constraint PK_DB_LOCK primary key (id)
);

create unique index if not exists NDX_LOCK_TYPE on DB_LOCK (lock_type);

create table if not exists DB_LOCK_HISTORY (
   id                   INT GENERATED BY DEFAULT AS IDENTITY not null,
   lock_id              INT                  not null,
   lock_type            CHAR(1)              not null
      constraint CKC_LOCK_TYPE_DB_LOCK_H check (lock_type in ('B','C','X','Y','Z')),
   lock_version         VARCHAR(50)          not null,
   hostname             VARCHAR(255)         not null,
   lock_acquired_on     TIMESTAMP WITH TIME ZONE not null default CURRENT_TIMESTAMP,
   lock_released_on     TIMESTAMP WITH TIME ZONE not null default CURRENT_TIMESTAMP,
   constraint PK_DB_LOCK_HISTORY primary key (id)
);

create index if not exists NDX_DATE on DB_LOCK_HISTORY (lock_acquired_on);

create index if not exists NDX_LOCK on DB_LOCK_HISTORY (lock_type, lock_version);

create table if not exists DB_LOCK_LATEST (
   lock_type            CHAR(1)              not null
      constraint CKC_LOCK_TYPE_DB_LOCK_L check (lock_type in ('B','C','X','Y','Z')),
   lock_version         VARCHAR(50)          not null,
   hostname             VARCHAR(255)         not null,
   lock_acquired_on     TIMESTAMP WITH TIME ZONE not null,
   constraint PK_DB_LOCK_LATEST primary key (lock_type)
);
