-- Oracle creation script for opentmf-db-lock-service.
-- Targets Oracle 12c+ (IDENTITY columns, TIMESTAMP WITH TIME ZONE).
-- Statement separator: '/' (required because this file contains PL/SQL
-- anonymous blocks with embedded semicolons). Each idempotency guard
-- catches ORA-00955 ("name is already used by an existing object") so the
-- script may be re-run safely.

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE DB_LOCK (
      id               NUMBER(10)           GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      lock_type        CHAR(1)              NOT NULL
        CONSTRAINT CKC_LOCK_TYPE_DB_LOCK CHECK (lock_type IN (''B'',''C'',''X'',''Y'',''Z'')),
      lock_version     VARCHAR2(50)         NOT NULL,
      hostname         VARCHAR2(255)        NOT NULL,
      created_on       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_DB_LOCK PRIMARY KEY (id)
    )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE UNIQUE INDEX NDX_LOCK_TYPE ON DB_LOCK (lock_type)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE DB_LOCK_HISTORY (
      id               NUMBER(10)           GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      lock_id          NUMBER(10)           NOT NULL,
      lock_type        CHAR(1)              NOT NULL
        CONSTRAINT CKC_LOCK_TYPE_DB_LOCK_H CHECK (lock_type IN (''B'',''C'',''X'',''Y'',''Z'')),
      lock_version     VARCHAR2(50)         NOT NULL,
      hostname         VARCHAR2(255)        NOT NULL,
      lock_acquired_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      lock_released_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_DB_LOCK_HISTORY PRIMARY KEY (id)
    )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE INDEX NDX_DATE ON DB_LOCK_HISTORY (lock_acquired_on)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE INDEX NDX_LOCK ON DB_LOCK_HISTORY (lock_type, lock_version)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE DB_LOCK_LATEST (
      lock_type        CHAR(1)              NOT NULL
        CONSTRAINT CKC_LOCK_TYPE_DB_LOCK_L CHECK (lock_type IN (''B'',''C'',''X'',''Y'',''Z'')),
      lock_version     VARCHAR2(50)         NOT NULL,
      hostname         VARCHAR2(255)        NOT NULL,
      lock_acquired_on TIMESTAMP WITH TIME ZONE NOT NULL,
      CONSTRAINT PK_DB_LOCK_LATEST PRIMARY KEY (lock_type)
    )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
